### ISSUE TITLE
Upload to hackage

### ISSUE THREAD

**Issue by lukehoersten** [jberryman/unagi-bloomfilter#1]
Any plans to upload to hackage?

**Comment by jberryman** [comment]
Hey Luke, yeah eventually for sure. It's just a project that's coming together slowly with several dependent parts. I won't be ready to release it for at least a month or two. I just stuck it up here because it exhibited a bug I was showing to GHC team. 

Thanks for the interest.

**Comment by lukehoersten** [comment]
Thanks
