### ISSUE TITLE
Exception during deserialization of appropriately-sized array

### ISSUE THREAD

**Issue by EButlerIV** [jberryman/unagi-bloomfilter#2]
The following program results in an exception of `*** Exception: BloomFilterException "Array is an unexpected size for a serialized bloom filter"` even though it seems like the parameters are within accepted ranges.

```
module Main where

import qualified Control.Concurrent.BloomFilter as Bloom
import qualified Data.ByteString.Char8 as BS

main :: IO ()
main = do
  sipKey <- pure $ (Bloom.SipKey 1 1)
  bloom <- Bloom.new sipKey 3 26 :: IO (Bloom.BloomFilter String)
  bloomBS <- Bloom.serialize bloom
  newBloom <- Bloom.deserialize sipKey bloomBS :: IO (Bloom.BloomFilter String)
  return ()
```
where `k=3`, `log21=2^26`, and `log2l + k*(logBase 2 wordSizeInBits) = 44`, (I think).

This fails for some reason, but larger filters, (k=6, log2l=28) are fine. Is there a good way to figure out what's going on?

**Comment by jberryman** [comment]
Thanks for reporting, I'll try to take a look this evening or tomorrow. Can you let me know your machine architecture and ghc version?
